var jokes = [

    "People say \"Mitch, why'd you get into comedy? Were you funny?\" \"No, I was just good at holding ice cream cones.\"",
    "Imagine being killed by a bow and arrow, that would suck. An arrow killed you? They would never solve the crime. \"Look at that dead guy... Let's go that way.\"",
    "I never had a piggy bank, but one time I had some bacon and it tasted an awful lot like change.",
    "When I think of a duck's friends, I think of more ducks, right? But, shit, he could have, like, a beaver in tow.",
    "I wish all my clothes were made out of blankets. That way, if I fall asleep with my clothes on, fuckin' A, I'm tucked in.",
    "I like to take a toothpick and throw it in the forest and say \"You're home!\"",
    "I remixed the remix... it was back to normal.",
    "You know that show \"My Three Sons\"? That'd be funny if it was called \"My One Dad\".",
    "Hey, you know what keeps me from acting? Fuckin'... auditions.",
    "I know a lot about cars, man. I can look at a car's headlights and tell you exactly which way it's going.",
    "I had a piece of Carefree sugarless gum... and I was still worried.",
    "If you have dentures, do not use artificial sweeteners because you will get a fake cavity.",
    "I gotta idea for sweat shops... air conditioning! Problem solved.",
    "People think I'm into sports just because I'm a man. I'm not into sports. I mean, I like Gatorade, but that's about as far as it goes.",
    "If you find yourself lost in the woods, fuck it, build a house. \"Well, I was lost, but now I live here. I have severely improved my predicament.\"",
    "I did comedy for a fundraiser once. We were trying to raise money to buy one of those machines that shows how much money has been raised.",
    "A fly was very close to being called a \"land\" because that's what it does half the time.",
    "I think foosball is a combination of soccer and shish kabobs.",
    "I wanted to buy a candle holder, but the store didn't have one. So I got a cake.",
    "If you're a fish, and you want to become a fish stick, you have to have very good posture.",
    "I wear a necklace now... because I like to know when I'm upside down.",
    "I got a door deal here, I'm working for 50% of the door and then tomorrow I'm working for 50% of the door and then on Sunday... I'm gonna have a door.",
    "My hotel doesn't have a 13th floor because of superstition. But, c'mon man, people on the 14th floor, you know what floor you're really on.",
    "I wear glasses. I stopped wearing 'em... because when you wear glasses and you talk to someone, you always think they're outside of a window.",
    "I like Kit Kats... unless I'm with four or more people.",
    "I drank some boiling water... because I wanted to whistle.",
    "I have a cheese shredder at home. That's a positive name for it: cheese shredder. They don't call it by its negative name because nobody would buy it... sponge ruiner.",
    "If I had nine of my fingers missing... I wouldn't type any slower.",
    "My hotel is haunted. I saw a sheet lying on the floor... must have been a ghost that had passed out.",
    "I got a vest. If I had my arms cut off, it would be a jacket.",
    "When you have a CD in a store, you have to do in-store appearances. If nobody shows up, I just pretend like I'm shopping.",
    "I never joined the Army because \"at ease\" was never that easy to me. Seemed rather \"uptight and still.\"",
    "If carrots got you drunk, rabbits would be fucked up.",
    "As a kid, I used to jump on beds. But as an adult, I do not sleep on trampolines.",
    "That would be cool if you lived with a monster... you would never get hiccups!",
    "If I was a headless horseman's horse, I would fuck with that dude. \"Yeah, we're going that way. We're not headed toward the hay.\"",
    "Imagine if the headless horseman had a headless horse, that would be fucking chaos. \"We need a head!\"",
    "I got a new headless horseman joke. I’d hate to be the headless horseman’s dentist. You wouldn’t make very much money.",
    "In Venice, Italy, they don't have streets, they have canals. So in Venice, Italy, we have to keep the kids off the canals.",
    "I would imagine if you could understand morse code, a tap dancer would drive you crazy.",
    "A snake bite emergency repair kit is a body bag.",
    "I don't own a watch because I want my arms to weigh the same.",
    "I got a business card... because I want to win some lunches.",
    "If you had a friend who was a tightrope walker and you were walking on the sidewalk with him, and he fell... that would be completely unacceptable.",
    "One time I had a Jack and Coke, it had a lime in it, and I saw that the lime was floating. That's good news, man. The next time I'm in a boat and it capsizes, I will reach for a lime.",
    "My manager takes 10% from me. Sometimes I work for free drinks. I bring him home a Jack and Coke.",
    "I play the guitar. I taught myself how to play the guitar, which was a bad decision because I didn't know how to play it. So I was a shitty teacher. I would never have went to me.",
    "You know there's a fishing show on TV? They catch the fish, but they let it go. They don't want to eat the fish, but they do want to make it late for something.",
    "Anybody here watch ESPN Classic? I saw a baseball game on there. The guy hit a foul ball. Fuckin' classic, man.",
    "I'm sick of Soup of the Day! It's time we make a decision. I want to know what the fuck soup from now on is.",
    "I got a jump rope. That thing's just a rope, man. You gotta make the jump thing happen.",
    "I read last year that MTV's Real World got 40,000 applications. That's amazing, man... such an even number.",
    "My sister wanted to be an actress. She never made it, but she does live in a trailer. She got half way. So it's like she's an actress, she just never gets called to the set.",
    "I got into an argument with a girlfriend inside of a tent. That's a bad place for an argument. Because then I tried to walk out and slam the flap.",
    "My fake plants died because I did not pretend to water them.",
    "I bought a $7 pen because I always lose pens and I got sick of not caring.",
    "I used to do drugs - I still do, but I used to, too.",
    "The depressing thing about tennis is that no matter how good I get, I'll never be as good as a wall.",
    "I haven't slept for ten days, because that would be too long.",
    "A burrito is a sleeping bag for ground beef.",
    "An escalator can never break - it can only become stairs.",
    "This shirt is 'dry-clean only' - which means it's dirty.",
    "When I was a boy, I laid in my twin-sized bed and wondered where my brother was.",
    "I find a duck's opinion of me is very much influenced by whether or not I have bread.",
    "I wish I could play little league now, I'd be way better than before.",
    "I love my FedEx guy cause he's a drug dealer and he doesn't even know it - and he's always on time.",
    "The last time I called 'shotgun', we had rented a limo, so I fucked up.",
    "This sign says \"IMPROV,\" but I had a bad set on Friday night, so yesterday they put an \"E\" on the end of it.",
    "I got an ant farm; them fellas didn't grow shit.",
    "I don't have a microwave oven, but I do have a clock that occasionally cooks stuff.",
    "I'm against picketing, but I don't know how to show it.",
    "I got my hair highlighted, because I felt some strands were more important than others.",
    "If you're flammable and have legs, you are never blocking a fire exit.",
    "People tell me how hard it is to stop smoking; I think it's about as hard as it is to start flossing.",
    "I'm a hard act to follow, because when I'm done, I take the microphone with me.",
    "You don't have to be sweaty and holding a basketball to enjoy a Gatorade; you could just be a thirsty dude - Gatorade forgets about this demographic!",
    "My friend asked me if I wanted a frozen banana, I said \"No, but I want a regular banana later, so... yeah.\"",
    "I'd hate to be a giraffe with a sore throat.",
    "I put fruit on top of my waffles, because I want something to brush off.",
    "I was gonna have my teeth whitened, but then I said fuck that, I'll just get a tan instead.",
    "When I was on acid I would see things like beams of light, and I would hear things that sounded an awful lot like car horns.",
    "One time, this guy handed me a picture of him, he said,\"Here's a picture of me when I was younger.\" Every picture is of you when you were younger.",
    "Is a hippopotamus a hippopotamus? Or just a really cool opotamus?",
    "I went to a record store, they said they specialized in hard-to-find records - nothing was alphabetized.",
    "A severed foot is the ultimate stocking stuffer.",
    "Onions make me sad. A lot of people don't realize that.",
    "If my kid couldn't draw I'd make sure that my kitchen magnets didn't work.",
    "When someone hands you a flyer, it's like they're saying \"Here, you throw this away.\"",
    "A dog is forever in the push-up position.",
    "I got a parrot and it talked, but it did not say I'm hungry, so it died.",
    "I'm sick of following my dreams, I'm going to ask them where they're going and hook up with them later.",
    "I turned to my friend and said \"How do you abbreviate Arkansas\". He said \"I don't know, just start spelling it, and then quit\".",
    "I like to play blackjack. I'm not addicted to gambling, I'm addicted to sitting in a semi-circle.",
    "I once saw a forklift lift a crate of forks. And it was way too literal for me.",
    "I think Bigfoot is blurry, that's the problem - it's not the photographer's fault.",
    "I order the club sandwich all the time and I'm not even a member. I don't know how I get away with it.",
    "Alcoholism is a disease, but it's the only one you can get yelled at for having.",
    "My belt holds my pants up, but the belt loops hold my belt up; so which one's the real hero?",
    "At the end of my letters, I like to write 'P.S. - this is what part of the alphabet would look like if Q and R were eliminated.'",
    "If Spiderman was real, and I was a criminal, and he shot me with his web, I would say, \"Dude, thanks for the hammock.\"",
    "Swiss Cheese is a rip-off - it's the only cheese I can bite into and miss.",
    "It's very dangerous to wave to people you don't know because what if they don't have hands? They'll think you're cocky.",
    "Y'know, you can't please all the people all the time - and last night, all those people were at my show."

]